services:
  - postgresql
before_script:
 - psql -c 'create database mavtest;' -U postgres
 - psql -U postgres -d mavtest -f docs/create_tables.sql
 - psql -U postgres -d mavtest -f docs/fill_tables.sql
 - cd src/MavenVideo
 - ls
language: java
jdk:
  - oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
